name: "Hello World"
description: "Greet someone"
inputs:
  node-version:
    description: "Node Version"
    required: true
    default: 20.x

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - uses: actions/cache@v3
      with:
        path: "**/node_modules"

        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - run: pnpm install
      shell: bash
